idf_component_register(SRCS "fault_monitor.cpp" "sm_events.cpp" "joints_storage.cpp" "CinematicsUtils.cpp" "can_msg_queue.c" "web.cpp" "wifi.c" "main.cpp" "state_machine.cpp" "communication_handler.cpp" "Joint.cpp" "Arm.cpp" "Config.cpp" "sm_events.cpp" "fault_monitor.cpp"
                    INCLUDE_DIRS "."
                    EMBED_FILES "www/index.html")